CREATE  DATABASE SA;

        CREATE TABLE  CLIENT (
            ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL ,
            EMAIL VARCHAR(50) NOT NULL
        );

        CREATE TABLE  SENTIMENT(
            ID INTEGER PRIMARY KEY  AUTO_INCREMENT NOT NULL ,
            AVIS VARCHAR(500),
            TYPE VARCHAR(100),
            CLIENT_ID INTEGER ,
            CONSTRAINT  client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)

        )